//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mywork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezume
    {
        public int Id { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Возраст { get; set; }
        public string Опыт_работы { get; set; }
        public string Образование { get; set; }
        public string Желаемый_доход { get; set; }
        public string О_себе { get; set; }
    }
}
