//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mywork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vakansii
    {
        public int Id { get; set; }
        public string Организация { get; set; }
        public string Должность { get; set; }
        public string Требования { get; set; }
        public string Функционал { get; set; }
        public string Формат_работы { get; set; }
        public string Доход { get; set; }
        public string График { get; set; }
        public string Условия { get; set; }
    }
}
